// Type definitions for the consulting-report template.
//
// This file is the contract between the template (primitives + types) and the
// project (the report instance that supplies the actual data). Projects import
// the types they need; they do NOT edit this file.
//
// Two families of types:
//
//   1. Strategic-assessment shapes — Finding, Recommendation, TimelinePhase,
//      and the ReportData interface composed of them. These power the default
//      scaffolded layout (executive summary, findings, recommendations, etc.).
//
//   2. Scoring-playbook shapes — RubricLevel, Dimension, Scorecard, etc. These
//      power rubric-style deliverables (an opportunity scoring playbook is one
//      example). Each is optional; projects use whichever apply.
//
// Adding a new section type? Add its interface here so all reports share the
// same vocabulary.

export interface Finding {
  id: string;
  title: string;
  description: string;
  evidence: string;
  source: string;
  severity: "critical" | "high" | "medium" | "low";
}

export interface Recommendation {
  id: string;
  title: string;
  description: string;
  priority: "immediate" | "short-term" | "long-term";
}

export interface TimelinePhase {
  phase: string;
  title: string;
  description: string;
  duration: string;
}

export interface ReportData {
  clientName: string;
  reportTitle: string;
  reportDate: string;
  classification: string;
  consultancyName: string;
  preTitle?: string;

  executiveSummary: {
    context: string;
    methodology: { interviewCount: number; roles: string[] };
    keyFindings: string[];
    primaryRecommendation: string;
    expectedOutcomes: string[];
  };

  situationAssessment: {
    currentState: string;
    clientAsk: string;
    whyNow: string;
  };

  findings: Finding[];

  riskAnalysis: {
    existentialRisks: string[];
    competitiveThreats: string[];
    timelinePressures: string;
  };

  strategicOpportunity: {
    goodNews: string;
    requirements: string[];
  };

  recommendations: Recommendation[];

  targetState: {
    description: string;
    keyCapabilities: string[];
    successMetrics: string[];
  };

  roadmap: TimelinePhase[];

  callToAction: {
    immediateSteps: string[];
    decisionPoints: string[];
    commitmentRequired: string;
  };
}

// --- Scoring-playbook shapes ---

export interface RubricLevel {
  /** Numeric label for this level (typically 1..N, but free-form). */
  score: number;
  label: string;
  anchor: string;
}

export interface Dimension {
  id: string;
  name: string;
  parenthetical?: string;
  definition: string;
  levels: RubricLevel[];
  scoringGuidance?: string[];
  /**
   * Optional note about who tunes this dimension's anchors and when.
   * Surfaced by the project's layout (often next to a "TUNABLE" marker).
   */
  tuningNote?: string;
}

export interface ScorecardGate {
  name: string;
  verdict: "pass" | "fail" | "n/a" | "flag";
  note?: string;
}

export interface ScorecardScore {
  dimensionId: string;
  dimensionLabel: string;
  /** Score for this dimension. Typically 1..N matching the rubric. */
  score: number;
  justification: string;
}

export interface Scorecard {
  id: string;
  index: number;
  name: string;
  outcome: string;
  inventoryRef?: string;
  gates: ScorecardGate[];
  scores: ScorecardScore[];
  total: number;
  /**
   * Free-form band label. The default `BandBadge` style map covers
   * "Strong" | "Promising" | "Park" | "Decline"; projects can use any
   * string and supply their own style map.
   */
  band: string;
  /**
   * Maximum possible score (used by Scorecard to render "total / maxTotal").
   * Defaults to 20 when omitted.
   */
  maxTotal?: number;
  weightingNote?: string;
  vetoTriggered: boolean;
  vetoNote?: string;
  recommendation: string;
  firstAction: string;
  owner: string;
  nextReview: string;
}

export interface ConfigurationParameter {
  name: string;
  currentValue: string;
  location: string;
  rationale?: string;
  /**
   * If true, this parameter is tunable by the report's owner. Renders a
   * marker next to the parameter name.
   */
  tunable?: boolean;
  /**
   * Optional label for the tunable marker (e.g., "Owner edit", "Tune at sync").
   * Defaults to "TUNABLE" when omitted.
   */
  tunableLabel?: string;
}

export interface TuningLogEntry {
  date: string;
  parameter: string;
  oldValue: string;
  newValue: string;
  rationale: string;
  approver: string;
}
